// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fldanplay/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(HistoriesTypeAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(OfflineCacheAdapter());
    registerAdapter(StorageAdapter());
    registerAdapter(StorageRecordAdapter());
    registerAdapter(StorageTypeAdapter());
    registerAdapter(VideoInfoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(HistoriesTypeAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(OfflineCacheAdapter());
    registerAdapter(StorageAdapter());
    registerAdapter(StorageRecordAdapter());
    registerAdapter(StorageTypeAdapter());
    registerAdapter(VideoInfoAdapter());
  }
}
